//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1FIT5032.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutritional_Value
    {
        public long Id { get; set; }
        public string Food { get; set; }
        public double Serving_Gram { get; set; }
        public double Calories { get; set; }
        public double Calories_From_Fat { get; set; }
        public double Total_Fat_Gram { get; set; }
        public double Total_Fat_Daily_Value_By_Precentage { get; set; }
        public double Sodium_Gram { get; set; }
        public double Sodium_Daily_Value_By_Precentage { get; set; }
        public double Potassium_Gram { get; set; }
        public double Potassium_Daily_Value_By_Precentage { get; set; }
        public double Total_Carbo_Hydrate_Gram { get; set; }
        public double Total_Carbo_Hydrate_Daily_Value_By_Precentage { get; set; }
        public double Dietary_Fiber_Gram { get; set; }
        public double Dietary_Fiber_Daily_Value_By_Precentage { get; set; }
        public double Sugar_Gram { get; set; }
        public double Protein_Gram { get; set; }
        public double Vitamin_A_Daily_Value_By_Precentage { get; set; }
        public double Vitamin_C_Daily_Value_By_Precentage { get; set; }
        public double Calcium_Daily_Value_By_Precentage { get; set; }
        public double Iron_Daily_Value_By_Precentage { get; set; }
        public Nullable<double> Saturated_Daily_Value_By_Precentage { get; set; }
        public Nullable<double> Saturated_Milligram { get; set; }
        public double Chole_Sterol_Daily_Value_By_Precentage { get; set; }
        public double Chole_Sterol_Milligram { get; set; }
        public string Food_Type { get; set; }
        public System.DateTime Date { get; set; }
    }
}
