//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1FIT5032.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Rating
    {
        public int Id { get; set; }
        // To Enforce Range Value Of 1 to 5
        [Range(1, 5, ErrorMessage = "The value must between 1 & 5")]
        [DisplayName("Store Rating")]
        public long Store_Rating { get; set; }
        [Required(ErrorMessage = "Please Enter A Value")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Please write a review between 3 to 300 characters long.")]
        public string Comment { get; set; }
        [DisplayName("User Id")]
        public string User_Id { get; set; }
        [DisplayName("Store Id")]
        public int Store_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Store Store { get; set; }
    }
}
