CREATE TABLE [dbo].[Nutritional_Value] (
    [Id]                                            BIGINT         IDENTITY (1, 1) NOT NULL,
    [Food]                                          NVARCHAR(MAX) NOT NULL,
    [Serving_Gram]                                  FLOAT NOT NULL,
    [Calories]                                      FLOAT NOT NULL,
    [Calories_From_Fat]                             FLOAT NOT NULL,
    [Total_Fat_Gram]                                FLOAT NOT NULL,
    [Total_Fat_Daily_Value_By_Precentage]           FLOAT NOT NULL,
    [Sodium_Gram]                                   FLOAT NOT NULL,
    [Sodium_Daily_Value_By_Precentage]              FLOAT NOT NULL,
    [Potassium_Gram]                                FLOAT NOT NULL,
    [Potassium_Daily_Value_By_Precentage]           FLOAT NOT NULL,
    [Total_Carbo_Hydrate_Gram]                      FLOAT NOT NULL,
    [Total_Carbo_Hydrate_Daily_Value_By_Precentage] FLOAT NOT NULL,
    [Dietary_Fiber_Gram]                            FLOAT NOT NULL,
    [Dietary_Fiber_Daily_Value_By_Precentage]       FLOAT NOT NULL,
    [Sugar_Gram]                                    FLOAT NOT NULL,
    [Protein_Gram]                                  FLOAT NOT NULL,
    [Vitamin_A_Daily_Value_By_Precentage]           FLOAT NOT NULL,
    [Vitamin_C_Daily_Value_By_Precentage]           FLOAT NOT NULL,
    [Calcium_Daily_Value_By_Precentage]             FLOAT NOT NULL,
    [Iron_Daily_Value_By_Precentage]                FLOAT NOT NULL,
    [Saturated_Daily_Value_By_Precentage]           FLOAT NULL,
    [Saturated_Milligram]                           FLOAT NULL,
    [Chole_Sterol_Daily_Value_By_Precentage]        FLOAT NOT NULL,
    [Chole_Sterol_Milligram]                        FLOAT NOT NULL,
    [Food_Type]                                     NVARCHAR (MAX) NOT NULL,
    [Date] DATE NULL, 
    CONSTRAINT [PK_Nutritional_Value] PRIMARY KEY CLUSTERED ([Id] ASC)
);

